### PR TITLE
Fix issues related to the JS proxy and properties

### LINKED ISSUE #23: Unable to assign `false` to boolean properties
Code to reproduce:

```js
const vtk = await window.vtkReady;
const actor = vtk.vtkActor();
actor.visibility= false;
console.log(actor.visibility);
```

Error message:

```
Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'visible'
    at <anonymous>:24:15
(anonymous) @ VM1304:24

```

@jourdain i will be taking care of this.

### LINKED ISSUE #24: Adding user-defined properties to objects does not work
One cannot add their own properties to the object returned be `vtk.vtkClassName()`.

```js
const vtk = await window.vtkReady;
const actor = vtk.vtkActor();
actor.myProperty = 1010;
console.log(actor.myProperty );
```

Console prints:

```
async(...A)=>i.decorateResult(await e.invoke(n,G(s),i.decorateArgs(A)))
```

because the proxy logic fails to find a C++ property `myProperty` on `vtkActor`. It assumes `myProperty` is a method, so it wraps around `wasm.invoke`.

What will help is if the object manager has API to find out if a method exists or not. I think it is not very hard to do thi.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/apply might also help in combination with `get`.

### PR DESCRIPTION
**Pull request by jspanchu**
closes https://github.com/Kitware/vtk-wasm/issues/23
closes #24

### CODE REVIEW

File: src/core/proxy.js [hunk 1]
```diff
@@ -101,34 +115,29 @@ export function createVtkObjectProxy(
...
+            vtkId,
+            toCxxName(prop),
+            wrapMethods.decorateArgs(args),
+          ),
+        );
       return target[prop];
     },
     set(target, property, value) {
-      if (propSetters[property]) {
+      if (propSetters[property] !== undefined) {
```
Comment (jourdain) [inline src/core/proxy.js]: Remove ` !== undefined`

**Review by jourdain — APPROVED** [review]
